---
  - hosts: all
    remote_user: ec2-user
    gather_facts: false
    tasks:
      - name: update
        yum:
          name: '*'
          state: latest

      - name: installing required packages to set up repository
        package:
          name: "{{ item }}"
          state: present
        loop:
          - yum-utils
          - lvm2
          - device-mapper-persistent-data

      - name: Adding docker repository
        command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        args:
          creates: /etc/yum.repos.d/docker-ce.repo

      - name: downloading container-selinux
        get_url:
          url: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.74-1.el7.noarch.rpm
          dest: /home/ec2-user/

      - name: installing container-selinux
        yum:
          name: container-selinux-2.74-1.el7.noarch.rpm
          state: present

      - name: installing docker-ce
        package:
          name: docker-ce
          state: present

      - name: starting and enabling the docker service
        service:
          name: docker
          state: started
          enabled: yes

      - name: downloading epel-release
        get_url:
          url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          dest: /home/ec2-user/

      - name: installing epel-release
        yum:
          name: epel-release-latest-7.noarch.rpm
          state: present

      - name: install pip
        yum:
          name: python-pip
          state: present

      - name: install docker python module
        pip:
          name: docker

      - name: pull an image
        docker_image:
         name: "{{ item }}"
        loop:
        - prom/prometheus
        - grafana/grafana

      - name: making a directory
        file:
          path: /home/ec2-user/prometheus
          state: directory

      - name: copying prometheus.yml to ec2
        copy:
          src: /home/gaurav/terraform/Prometheus/prometheus_ansible/prometheus.yml
          dest: /home/ec2-user/prometheus/

      - name: launch a prometheus container
        docker_container:
         name: prometheus
         image: prom/prometheus
         state: started
         auto_remove: yes
         ports:
           - "9090:9090"
         volumes:
           - /home/ec2-user/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

      - name: launch grafana container
        docker_container:
          name: grafana
          image: grafana/grafana
          state: started
          ports:
            - "3000:3000"
